# Generated by Django 5.1.1 on 2024-09-29 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solpedcaf', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='modulo',
            new_name='pagina_inicial',
        ),
    ]
