# Generated by Django 5.1.1 on 2024-10-06 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solpedcaf', '0002_rename_modulo_pagina_inicial'),
    ]

    operations = [
        migrations.CreateModel(
            name='plagas_y_enfermedades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='modulos')),
                ('urlDestino', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
