# Generated by Django 5.1.1 on 2024-10-06 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solpedcaf', '0004_etapa_de_crecimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapa_de_crecimiento',
            name='urlDestino',
        ),
    ]
