# Generated by Django 5.1.1 on 2024-10-07 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solpedcaf', '0008_etapa_de_floracion_alter_etapa_de_crecimiento_imagen_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='consejos_para_su_cultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='modulos')),
                ('urlDestino', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
