# Generated by Django 5.1.1 on 2024-10-09 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solpedcaf', '0014_soluciones_para_su_cultivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soluciones_para_su_cultivo',
            old_name='afectacion',
            new_name='titulo',
        ),
    ]
