# Generated by Django 5.1.1 on 2024-10-10 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solpedcaf', '0015_rename_afectacion_soluciones_para_su_cultivo_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa_de_plantacion',
            name='urldestino',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
