# Generated by Django 5.1.1 on 2024-10-10 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solpedcaf', '0016_etapa_de_plantacion_urldestino'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa_de_plantacion',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='modulos'),
        ),
        migrations.AddField(
            model_name='etapa_de_plantacion',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to='modulos'),
        ),
    ]
