# Generated by Django 5.1.1 on 2024-10-13 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solpedcaf', '0017_etapa_de_plantacion_imagen2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soluciones_para_su_cultivo',
            old_name='urlDestino',
            new_name='implemento',
        ),
        migrations.RemoveField(
            model_name='soluciones_para_su_cultivo',
            name='descripcion',
        ),
        migrations.AddField(
            model_name='soluciones_para_su_cultivo',
            name='metodo_de_aplicacion',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='soluciones_para_su_cultivo',
            name='toxicidad',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
