# Generated by Django 5.1.1 on 2024-10-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solpedcaf', '0018_rename_urldestino_soluciones_para_su_cultivo_implemento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soluciones_para_su_cultivo',
            name='imagen',
            field=models.ImageField(null=True, upload_to='media/implementos'),
        ),
    ]
