# Generated by Django 5.1.1 on 2024-10-13 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solpedcaf', '0019_soluciones_para_su_cultivo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soluciones_para_su_cultivo',
            name='imagen',
            field=models.ImageField(null=True, upload_to='implementos'),
        ),
    ]
