# Generated by Django 5.1.1 on 2024-10-13 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solpedcaf', '0020_alter_soluciones_para_su_cultivo_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='soluciones_para_su_cultivo',
            old_name='imagen',
            new_name='imagen1',
        ),
        migrations.RenameField(
            model_name='soluciones_para_su_cultivo',
            old_name='implemento',
            new_name='implemento1',
        ),
        migrations.RenameField(
            model_name='soluciones_para_su_cultivo',
            old_name='metodo_de_aplicacion',
            new_name='metodo_de_aplicacion1',
        ),
        migrations.RenameField(
            model_name='soluciones_para_su_cultivo',
            old_name='toxicidad',
            new_name='toxicidad1',
        ),
    ]
