# Generated by Django 5.1.1 on 2024-10-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solpedcaf', '0021_rename_imagen_soluciones_para_su_cultivo_imagen1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='soluciones_para_su_cultivo',
            name='imagen2',
            field=models.ImageField(null=True, upload_to='implementos'),
        ),
        migrations.AddField(
            model_name='soluciones_para_su_cultivo',
            name='imagen3',
            field=models.ImageField(null=True, upload_to='implementos'),
        ),
        migrations.AddField(
            model_name='soluciones_para_su_cultivo',
            name='implemento2',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='soluciones_para_su_cultivo',
            name='implemento3',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='soluciones_para_su_cultivo',
            name='metodo_de_aplicacion2',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='soluciones_para_su_cultivo',
            name='metodo_de_aplicacion3',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='soluciones_para_su_cultivo',
            name='toxicidad2',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='soluciones_para_su_cultivo',
            name='toxicidad3',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
