# Generated by Django 5.1.1 on 2024-10-17 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solpedcaf', '0022_soluciones_para_su_cultivo_imagen2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etapa_de_crecimiento',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='modulos'),
        ),
        migrations.AddField(
            model_name='etapa_de_crecimiento',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to='modulos'),
        ),
        migrations.AddField(
            model_name='etapa_de_crecimiento',
            name='urldestino',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='etapa_de_floracion',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='modulos'),
        ),
        migrations.AddField(
            model_name='etapa_de_floracion',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to='modulos'),
        ),
        migrations.AddField(
            model_name='etapa_de_floracion',
            name='urldestino',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='etapa_de_fructificacion',
            name='imagen2',
            field=models.ImageField(blank=True, null=True, upload_to='modulos'),
        ),
        migrations.AddField(
            model_name='etapa_de_fructificacion',
            name='imagen3',
            field=models.ImageField(blank=True, null=True, upload_to='modulos'),
        ),
        migrations.AddField(
            model_name='etapa_de_fructificacion',
            name='urldestino',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
