# Generated by Django 5.1.1 on 2024-10-17 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solpedcaf', '0024_remove_etapa_de_floracion_imagen2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etapa_de_crecimiento',
            name='imagen2',
        ),
        migrations.RemoveField(
            model_name='etapa_de_crecimiento',
            name='imagen3',
        ),
        migrations.RemoveField(
            model_name='etapa_de_floracion',
            name='imagen3',
        ),
        migrations.RemoveField(
            model_name='etapa_de_fructificacion',
            name='imagen2',
        ),
        migrations.RemoveField(
            model_name='etapa_de_fructificacion',
            name='imagen3',
        ),
        migrations.RemoveField(
            model_name='etapa_de_plantacion',
            name='imagen2',
        ),
        migrations.RemoveField(
            model_name='etapa_de_plantacion',
            name='imagen3',
        ),
    ]
