# Generated by Django 5.1.1 on 2024-10-17 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solpedcaf', '0025_remove_etapa_de_crecimiento_imagen2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='broca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=10)),
                ('sintomas', models.TextField()),
                ('sintomas2', models.TextField(default=0)),
                ('sintomas3', models.TextField(default=0)),
                ('descripcion', models.TextField()),
                ('mdp', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='modulos')),
            ],
        ),
    ]
