# Generated by Django 5.1.1 on 2024-10-18 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solpedcaf', '0026_broca'),
    ]

    operations = [
        migrations.CreateModel(
            name='roya',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=10)),
                ('sintomas', models.TextField()),
                ('sintomas2', models.TextField(default=0)),
                ('sintomas3', models.TextField(default=0)),
                ('descripcion', models.TextField()),
                ('mdp', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='modulos')),
            ],
        ),
    ]
