# Generated by Django 5.1.1 on 2024-10-18 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solpedcaf', '0027_roya'),
    ]

    operations = [
        migrations.AddField(
            model_name='broca',
            name='urlDestino',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='roya',
            name='urlDestino',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
