# Generated by Django 5.1.1 on 2024-11-18 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solpedcaf', '0030_alter_usuario_rol'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
    ]
