# Generated by Django 5.1.1 on 2024-11-18 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solpedcaf', '0033_remove_usuario_f_nacimiento_usuario_permisos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='permisos',
            field=models.DateField(null=True),
        ),
    ]
