# Generated by Django 5.1.1 on 2024-11-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solpedcaf', '0034_alter_usuario_permisos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='permisos',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
