# Generated by Django 5.1.1 on 2024-11-18 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('solpedcaf', '0035_alter_usuario_permisos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='edad',
        ),
        migrations.AddField(
            model_name='usuario',
            name='area',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
